"""Added generic_text attribute on SimpleEntity

Revision ID: 5999269aad30
Revises: 182f44ce5f07
Create Date: 2014-06-02 15:17:27.961000

"""

# revision identifiers, used by Alembic.
revision = '5999269aad30'
down_revision = '182f44ce5f07'

from alembic import op
import sqlalchemy as sa

def upgrade():

    op.add_column(
        'SimpleEntities',
        sa.Column('generic_text', sa.Text(), nullable=False)
    )

    '''
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SimpleEntities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('generic_text', sa.Text(), nullable=True),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('html_style', sa.String(length=64), nullable=True),
    sa.Column('html_class', sa.String(length=64), nullable=True),
    sa.Column('stalker_version', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['Users.id'], name='xc', use_alter=True),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['Links.id'], name='z', use_alter=True),
    sa.ForeignKeyConstraint(['type_id'], ['Types.id'], name='y', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['Users.id'], name='xu', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    '''





def downgrade():

    op.drop_column('SimpleEntities', 'generic_text')

    '''
    op.create_table('simpleentities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('generic_text', mysql.TEXT(), nullable=True),
    sa.Column('thumbnail_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('html_style', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('html_class', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('stalker_version', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], [u'users.id'], name=u'xc'),
    sa.ForeignKeyConstraint(['thumbnail_id'], [u'links.id'], name=u'z'),
    sa.ForeignKeyConstraint(['type_id'], [u'types.id'], name=u'y'),
    sa.ForeignKeyConstraint(['updated_by_id'], [u'users.id'], name=u'xu'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    '''
