"""Created Variant class.

Revision ID: 91ed52b72b82
Revises: 644f5251fc0d
Create Date: 2024-11-22 07:57:46.848687
"""

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91ed52b72b82"
down_revision = "644f5251fc0d"


def upgrade():
    """Upgrade the tables."""
    op.create_table(
        "Variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["Tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "Projects",
        "fps",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=True,
    )
    op.alter_column(
        "Shots",
        "fps",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=3),
        existing_nullable=True,
    )


def downgrade():
    """Downgrade the tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Shots",
        "fps",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "Projects",
        "fps",
        existing_type=sa.Float(precision=3),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.drop_table("Variants")
